### ISSUE TITLE
ImportError: No module named 'newton'

### ISSUE THREAD

**Issue by nedlrichards** [olivierverdier/odelab#1]
I am excited about this module, but I can't seem to run anything because of the ImportError above. For example, the result of nosetests tests:

bash-4.2$ nosetests tests

```
/home/e2richards/external_python/odelab/odelab/store.py:126: UserWarning: PyTables is not available; falling back to a simpler store
  warnings.warn('PyTables is not available; falling back to a simpler store')
EEEEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named newton)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/e2richards/external_python/odelab/tests/scheme/test_constrained.py", line 5, in <module>
    from odelab.scheme import *
  File "/home/e2richards/external_python/odelab/odelab/__init__.py", line 2, in <module>
    from .scheme import Scheme
  File "/home/e2richards/external_python/odelab/odelab/scheme/__init__.py", line 19, in <module>
    import newton as _rt
ImportError: No module named newton
```

I installed odelab from pip3.4.

Thanks for any help.

**Comment by olivierverdier** [comment]
You should also install the dependencies, you do that with `pip install -r requirements.txt .`. Feel free to reopen if you still have problems.
